// Typed access to the build-time word analysis behind /word-map.
//
// The JSON is generated by scripts/generate-word-stats.mjs and imported as a
// module rather than fetched, so the page renders synchronously and
// scripts/prerender.mjs captures the cloud as real HTML. That is what gives
// the page a no-JavaScript fallback and something for crawlers to read.
//
// To change what is counted, edit scripts/lib/word-map-config.mjs and run
// `npm run generate:words`.

import raw from "../data/word-stats.json";

/** A review the analysis drew from. Indexes into this array are used below. */
export interface WordReview {
  slug: string;
  title: string;
  series: number;
  episode: number;
  episodeEnd?: number;
}

/** One word (or character name), with its breakdown. */
export interface WordEntry {
  word: string;
  /** Total mentions across every review in scope. */
  count: number;
  /** How many distinct reviews mention it. */
  reviews: number;
  /** Series number (as a string key) → mentions in that series. */
  series: Record<string, number>;
  /** [index into `reviews`, mentions in that review] pairs, sorted by index. */
  episodes: [number, number][];
}

export interface WordStatsSummary {
  reviewsAnalysed: number;
  totalWords: number;
  uniqueMeaningfulWords: number;
  topWord: string | null;
  topWordCount: number;
  topCharacter: string | null;
  topCharacterCount: number;
}

export interface WordStats {
  generatedFrom: { reviewCount: number; seriesPresent: number[] };
  tuning: { cloudSize: number; heatMapWords: number; minTotalCount: number };
  reviews: WordReview[];
  stats: WordStatsSummary;
  words: WordEntry[];
  characters: WordEntry[];
}

// The JSON's tuple types widen to number[] on import, so assert the shape we
// know the generator produces.
const stats = raw as unknown as WordStats;

export function getWordStats(): WordStats {
  return stats;
}

/** Which series actually have reviews. Drives the filter buttons. */
export function getSeriesWithReviews(): number[] {
  return stats.generatedFrom.seriesPresent;
}

export type WordMode = "words" | "characters";

/**
 * Entries for a mode, narrowed to one series.
 *
 * Passing `null` for series returns the totals unchanged. Otherwise counts,
 * review totals and episode lists are all recomputed against that series
 * only, and words that never appear in it drop out.
 *
 * Re-sorted by count then alphabetically, matching the generator's ordering
 * so a filtered view is as stable as the unfiltered one.
 */
export function entriesForSeries(
  mode: WordMode,
  series: number | null,
): WordEntry[] {
  const source = mode === "characters" ? stats.characters : stats.words;
  if (series === null) return source;

  const inSeries = new Set(
    stats.reviews
      .map((review, index) => ({ review, index }))
      .filter(({ review }) => review.series === series)
      .map(({ index }) => index),
  );

  return source
    .map((entry) => {
      const episodes = entry.episodes.filter(([index]) => inSeries.has(index));
      const count = episodes.reduce((sum, [, n]) => sum + n, 0);
      return {
        word: entry.word,
        count,
        reviews: episodes.length,
        series: { [series]: count },
        episodes,
      } satisfies WordEntry;
    })
    .filter((entry) => entry.count > 0)
    .sort((a, b) =>
      b.count === a.count
        ? a.word.localeCompare(b.word, "en")
        : b.count - a.count,
    );
}

/**
 * Stable pseudo-random ordering for the cloud.
 *
 * Sorting a cloud by frequency looks like a ranked list, so the sizes need
 * mixing. Using a hash of the word itself — rather than a shuffle — means the
 * arrangement is identical on every build: adding a review slots new words in
 * without rearranging the ones already there.
 */
function stableHash(word: string): number {
  let hash = 2166136261;
  for (let i = 0; i < word.length; i += 1) {
    hash ^= word.charCodeAt(i);
    hash = Math.imul(hash, 16777619);
  }
  return hash >>> 0;
}

export function scatterForCloud(entries: WordEntry[]): WordEntry[] {
  return [...entries].sort((a, b) => stableHash(a.word) - stableHash(b.word));
}

/**
 * Map a count onto a 1–7 weight tier used for both font size and ink.
 *
 * Square-rooted, because raw frequency is far too steep: the top word runs
 * about thirty times the tail, and a linear scale renders the tail invisible.
 */
export function weightTier(count: number, max: number, min: number): number {
  if (max <= min) return 4;
  const scale = (Math.sqrt(count) - Math.sqrt(min)) / (Math.sqrt(max) - Math.sqrt(min));
  return Math.min(7, Math.max(1, Math.round(1 + scale * 6)));
}

/** "16 mentions across 4 reviews" — used in titles, labels and the panel. */
export function mentionSummary(entry: WordEntry): string {
  const mentions = `${entry.count} mention${entry.count === 1 ? "" : "s"}`;
  const reviews = `${entry.reviews} review${entry.reviews === 1 ? "" : "s"}`;
  return `${mentions} across ${reviews}`;
}
